server:
  port: 8091 # 节点自身的HTTP服务端口
spring:
  aop:
    proxy-target-class: true
block:
  difficulty: 4
  p2pport: 7001 # 节点自身的P2P服务端口
  ## 要连接的初始节点地址列表
  initialPeers:
    - ws://127.0.0.1:7002
    - ws://127.0.0.1:7003
    ## - ws://192.168.0.101:7004